apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-exam-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "exam-deployment"
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 15
