apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "exam-deployment"
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "exam"
    spec:
      containers:
        - name: "exam"
          image: "sarson.azurecr.io/exam"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 400m
              memory: 400Mi
          env:
            - name: DEPLOYED
              valueFrom:
                secretKeyRef:
                  name: semester3-secrets
                  key: DEPLOYED
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: semester3-secrets
                  key: USER
            - name: PW
              valueFrom:
                secretKeyRef:
                  name: semester3-secrets
                  key: PW
            - name: CONNECTION_STR
              valueFrom:
                secretKeyRef:
                  name: semester3-secrets
                  key: CONNECTION_STR
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: semester3-secrets
                  key: SECRET
