on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sarson.azurecr.io
        username: ${{ secrets.acr_sarson_username }}
        password: ${{ secrets.acr_sarson_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sarson.azurecr.io/exam:${{ github.sha }}
        docker push sarson.azurecr.io/exam:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_exam_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep exama687 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace exama687`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: exama687
        container-registry-url: sarson.azurecr.io
        container-registry-username: ${{ secrets.acr_sarson_username }}
        container-registry-password: ${{ secrets.acr_sarson_password }}
        secret-name: examdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: exama687
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          sarson.azurecr.io/exam:${{ github.sha }}
        imagepullsecrets: |
          examdockerauth